# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5c7feaecdbc211e0e3d4f1364526866cb495bb82de99ef906169d42020f572335891648889c856f5d8c0184beee7863a3dde8b0ce6bdc495f499573304af149

test:
  secret_key_base: e1c8220f015e2dc7de4173ed6d61ee1d738a4c4aa277a8302db3c27dbdab35809a308f0521916b46caf8ccdc2878730ac3688fdee6e3163c29491950f5ec240e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
